<?php

namespace GitsyncBundle\Repository;

/**
 * GitsyncRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GitsyncRepository extends \Doctrine\ORM\EntityRepository
{
}
